#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
OVERRIDE_FILE="$SCRIPT_DIR/docker-compose.override.yml"
CADDYFILE="$SCRIPT_DIR/Caddyfile"

# -------------------------------
# Domain / hostname choice
# -------------------------------
echo ""
echo "=== Synkronus quickstart installer ==="
echo ""
read -p "Do you have a domain name pointing to this server? (y/n) [n]: " HAS_DOMAIN
HAS_DOMAIN="${HAS_DOMAIN:-n}"

if [[ "$HAS_DOMAIN" =~ ^[yY] ]]; then
    MODE="domain"
    read -p "Enter your domain name (e.g. synkronus.example.com): " SITE_HOST
    if [ -z "$SITE_HOST" ]; then
        echo "ERROR: Domain name is required."
        exit 1
    fi
    echo "  → Caddy will provision a TLS certificate automatically."
else
    MODE="no-domain"
    read -p "Enter this server's public IP (or 'localhost' for local-only, no TLS) [localhost]: " USER_IP
    USER_IP="${USER_IP:-localhost}"
    if [ "$USER_IP" = "localhost" ] || [ "$USER_IP" = "127.0.0.1" ]; then
        SITE_HOST=""
        USE_TLS=false
        echo "  → Using port 80 only (no TLS). For TLS, use your server's public IP and <ip>.sslip.io next time."
    else
        # Use sslip.io so we can still get a real TLS cert (Let's Encrypt)
        SITE_HOST="${USER_IP}.sslip.io"
        USE_TLS=true
        echo "  → Using https://${SITE_HOST}/ — Caddy will provision a TLS certificate automatically."
    fi
fi
echo ""

# -------------------------------
# Auto-suggest instance name
# -------------------------------
suggest_name() {
    num=$(shuf -i 10000-99999 -n 1 2>/dev/null || echo $((10000 + RANDOM % 90000)))
    echo "s$num"
}

INSTANCE_NAME=$(suggest_name)
echo "Instance name: $INSTANCE_NAME"
echo ""

# -------------------------------
# Generate credentials (safe for use in YAML)
# -------------------------------
POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/=+' | cut -c1-32)
ADMIN_USERNAME="admin_$(openssl rand -hex 3)"
ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '/=+' | cut -c1-24)
JWT_SECRET=$(openssl rand -base64 32 | tr -d '/=+' | cut -c1-43)

# -------------------------------
# Update docker-compose.yml (credentials only)
# -------------------------------
if [ ! -f "$COMPOSE_FILE" ]; then
    echo "ERROR: docker-compose.yml not found at $COMPOSE_FILE"
    exit 1
fi

echo "Updating docker-compose.yml with generated credentials..."
sed -e "s/strong_password/$POSTGRES_PASSWORD/g" \
    -e "s/please_change_the_username/$ADMIN_USERNAME/g" \
    -e "s/change_the_password_as_well/$ADMIN_PASSWORD/g" \
    -e "s|rcN76PE4cYMYZ9D3iy71eBqHsZ4feddcdAF7Zlsfom0=|$JWT_SECRET|g" \
    "$COMPOSE_FILE" > "$COMPOSE_FILE.tmp"
mv "$COMPOSE_FILE.tmp" "$COMPOSE_FILE"

# -------------------------------
# Caddy in front (auto TLS when SITE_HOST is set)
# -------------------------------
if [ -n "$SITE_HOST" ]; then
    # Caddy will obtain and renew a Let's Encrypt cert for this hostname
    cat > "$CADDYFILE" << CADDY_EOF
# Generated by install.sh — Caddy auto-provisions TLS for $SITE_HOST
$SITE_HOST {
    reverse_proxy synkronus:8080
}
CADDY_EOF
else
    # Local-only: HTTP on port 80, no TLS (listen on all interfaces for Docker)
    cat > "$CADDYFILE" << 'CADDY_EOF'
# Generated by install.sh — local-only (no TLS)
:80 {
    reverse_proxy synkronus:8080
}
CADDY_EOF
fi

# -------------------------------
# docker-compose.override.yml: Caddy
# -------------------------------
if [ -n "$SITE_HOST" ]; then
    cat > "$OVERRIDE_FILE" << OVERRIDE_EOF
# Generated by install.sh — Caddy with automatic TLS for $SITE_HOST
services:
  synkronus:
    ports: []   # only via Caddy

  caddy:
    image: docker.io/caddy:2-alpine
    container_name: synkronus_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${SCRIPT_DIR}/Caddyfile:/etc/caddy/Caddyfile:ro"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - synkronus
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
OVERRIDE_EOF
else
    cat > "$OVERRIDE_FILE" << OVERRIDE_EOF
# Generated by install.sh — Caddy (port 80 only, no TLS)
services:
  synkronus:
    ports: []   # only via Caddy

  caddy:
    image: docker.io/caddy:2-alpine
    container_name: synkronus_caddy
    ports:
      - "80:80"
    volumes:
      - "${SCRIPT_DIR}/Caddyfile:/etc/caddy/Caddyfile:ro"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - synkronus
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
OVERRIDE_EOF
fi

echo "Caddyfile and docker-compose.override.yml written."
echo ""
echo "=== Credentials (save these) ==="
echo "  Instance:     $INSTANCE_NAME"
echo "  Admin user:   $ADMIN_USERNAME"
echo "  Admin pass:   $ADMIN_PASSWORD"
echo "  JWT secret:   (stored in docker-compose.yml)"
echo ""
echo "=== Next steps ==="
echo "  podman compose up -d"
echo "  podman compose logs -f caddy"
echo ""
echo "  Upgrading from a pre-release layout (app-bundles / app-bundle-versions)?"
echo "  See upgrade-path.md and utilities/migrate-synkronus-data.sh (stop the stack first)."
echo "  Backup attachments / DB from running containers: utilities/backup-attachments.sh, utilities/backup-db.sh"
echo ""
if [ -n "$SITE_HOST" ]; then
    echo "  Synkronus will be at https://${SITE_HOST}/"
    echo "  (Caddy obtains the TLS certificate on first request.)"
else
    echo "  Synkronus will be at http://localhost/"
fi
echo ""
